ALTER TABLE Contracts ADD COLUMN IF NOT EXISTS HomeownerSignatureBase64 TEXT;
ALTER TABLE Contracts ADD COLUMN IF NOT EXISTS ContractorSignatureBase64 TEXT;
ALTER TABLE Contracts ADD COLUMN IF NOT EXISTS TemplatePdfUrl TEXT;
ALTER TABLE Contracts ADD COLUMN IF NOT EXISTS SignedPdfUrl TEXT;
